
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "BEEP CALL CALLPY CASE DEFAULT ENDSTEP ENDSWITCH HANGUP ID NEWLINE SPEAK STEP STR SWITCH VAR WAITjob : newlines \n               | newlines stepdecl job\n        stepdecl : STEP ID expressions ENDSTEP\n        \n        expressions : newlines\n                    | NEWLINE expression expressions\n        \n        expression : oneline\n                   | switch\n        \n        id : ID\n        \n        oneline : VAR '=' terms\n                | SPEAK terms\n                | CALLPY id va_args\n                | BEEP\n                | WAIT terms\n                | CALL id va_args\n                | HANGUP\n        \n        switch : SWITCH VAR  switch_body ENDSWITCH\n        \n        switch_body : cases\n                    | cases default\n        \n        cases   : newlines\n                | NEWLINE case cases\n        \n        default : DEFAULT oneline NEWLINE\n        \n        case    : CASE STR oneline\n        \n        terms : term \n              | term '+' terms\n        \n        term    : VAR \n        \n        term    : STR\n        \n        va_args : empty \n                | term va_args\n        \n        empty :\n        \n        newlines    : NEWLINE\n                    | empty\n        "
    
_lr_action_items = {'NEWLINE':([0,5,8,12,13,14,15,19,22,26,27,28,29,30,31,32,33,34,35,37,38,39,40,45,46,47,50,52,56,],[3,3,11,-3,11,-6,-7,-12,-15,-10,-23,-25,-26,-29,-8,-13,-29,44,-9,-11,-27,-29,-14,-24,-28,-16,44,55,-22,]),'STEP':([0,2,3,4,5,12,],[-29,6,-30,-31,-29,-3,]),'$end':([0,1,2,3,4,5,7,12,],[-29,0,-1,-30,-31,-29,-2,-3,]),'ENDSTEP':([4,8,9,10,11,13,14,15,19,22,24,26,27,28,29,30,31,32,33,35,37,38,39,40,45,46,47,],[-31,-29,12,-4,-30,-29,-6,-7,-12,-15,-5,-10,-23,-25,-26,-29,-8,-13,-29,-9,-11,-27,-29,-14,-24,-28,-16,]),'DEFAULT':([4,19,22,26,27,28,29,30,31,32,33,34,35,37,38,39,40,42,43,44,45,46,50,53,56,],[-31,-12,-15,-10,-23,-25,-26,-29,-8,-13,-29,-29,-9,-11,-27,-29,-14,49,-19,-30,-24,-28,-29,-20,-22,]),'ENDSWITCH':([4,19,22,26,27,28,29,30,31,32,33,34,35,37,38,39,40,41,42,43,44,45,46,48,50,53,55,56,],[-31,-12,-15,-10,-23,-25,-26,-29,-8,-13,-29,-29,-9,-11,-27,-29,-14,47,-17,-19,-30,-24,-28,-18,-29,-20,-21,-22,]),'ID':([6,18,21,],[8,31,31,]),'VAR':([11,17,20,23,25,28,29,30,31,33,36,39,49,54,],[16,28,28,34,28,-25,-26,28,-8,28,28,28,16,16,]),'SPEAK':([11,49,54,],[17,17,17,]),'CALLPY':([11,49,54,],[18,18,18,]),'BEEP':([11,49,54,],[19,19,19,]),'WAIT':([11,49,54,],[20,20,20,]),'CALL':([11,49,54,],[21,21,21,]),'HANGUP':([11,49,54,],[22,22,22,]),'SWITCH':([11,],[23,]),'=':([16,],[25,]),'STR':([17,20,25,28,29,30,31,33,36,39,51,],[29,29,29,-25,-26,29,-8,29,29,29,54,]),'+':([27,28,29,],[36,-25,-26,]),'CASE':([44,],[51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'job':([0,5,],[1,7,]),'newlines':([0,5,8,13,34,50,],[2,2,10,10,43,43,]),'empty':([0,5,8,13,30,33,34,39,50,],[4,4,4,4,38,38,4,38,4,]),'stepdecl':([2,],[5,]),'expressions':([8,13,],[9,24,]),'expression':([11,],[13,]),'oneline':([11,49,54,],[14,52,56,]),'switch':([11,],[15,]),'terms':([17,20,25,36,],[26,32,35,45,]),'term':([17,20,25,30,33,36,39,],[27,27,27,39,39,27,39,]),'id':([18,21,],[30,33,]),'va_args':([30,33,39,],[37,40,46,]),'switch_body':([34,],[41,]),'cases':([34,50,],[42,53,]),'default':([42,],[48,]),'case':([44,],[50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> job","S'",1,None,None,None),
  ('job -> newlines','job',1,'p_job','Parser.py',27),
  ('job -> newlines stepdecl job','job',3,'p_job','Parser.py',28),
  ('stepdecl -> STEP ID expressions ENDSTEP','stepdecl',4,'p_stepdecl','Parser.py',36),
  ('expressions -> newlines','expressions',1,'p_expressions','Parser.py',42),
  ('expressions -> NEWLINE expression expressions','expressions',3,'p_expressions','Parser.py',43),
  ('expression -> oneline','expression',1,'p_expression','Parser.py',52),
  ('expression -> switch','expression',1,'p_expression','Parser.py',53),
  ('id -> ID','id',1,'p_id','Parser.py',59),
  ('oneline -> VAR = terms','oneline',3,'p_oneline','Parser.py',65),
  ('oneline -> SPEAK terms','oneline',2,'p_oneline','Parser.py',66),
  ('oneline -> CALLPY id va_args','oneline',3,'p_oneline','Parser.py',67),
  ('oneline -> BEEP','oneline',1,'p_oneline','Parser.py',68),
  ('oneline -> WAIT terms','oneline',2,'p_oneline','Parser.py',69),
  ('oneline -> CALL id va_args','oneline',3,'p_oneline','Parser.py',70),
  ('oneline -> HANGUP','oneline',1,'p_oneline','Parser.py',71),
  ('switch -> SWITCH VAR switch_body ENDSWITCH','switch',4,'p_switch','Parser.py',80),
  ('switch_body -> cases','switch_body',1,'p_switch_body','Parser.py',87),
  ('switch_body -> cases default','switch_body',2,'p_switch_body','Parser.py',88),
  ('cases -> newlines','cases',1,'p_cases','Parser.py',94),
  ('cases -> NEWLINE case cases','cases',3,'p_cases','Parser.py',95),
  ('default -> DEFAULT oneline NEWLINE','default',3,'p_default','Parser.py',105),
  ('case -> CASE STR oneline','case',3,'p_case','Parser.py',111),
  ('terms -> term','terms',1,'p_terms','Parser.py',117),
  ('terms -> term + terms','terms',3,'p_terms','Parser.py',118),
  ('term -> VAR','term',1,'p_term_var','Parser.py',128),
  ('term -> STR','term',1,'p_term_str','Parser.py',134),
  ('va_args -> empty','va_args',1,'p_va_args','Parser.py',140),
  ('va_args -> term va_args','va_args',2,'p_va_args','Parser.py',141),
  ('empty -> <empty>','empty',0,'p_empty','Parser.py',151),
  ('newlines -> NEWLINE','newlines',1,'p_newlines','Parser.py',157),
  ('newlines -> empty','newlines',1,'p_newlines','Parser.py',158),
]
